In [5]:
import numpy as np

In [6]:
#Write a NumPy program to create a 5×5 matrix with values 1,2,3,…,25.
array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
#Generate a 4×4 identity matrix using NumPy
a = np.array([
    [1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]
])
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [10]:
#Create a 1D array of numbers from 100 to 200 with step size 10.
a = np.arange(100,201,10)

print(a)

[100 110 120 130 140 150 160 170 180 190 200]


In [17]:
#Generate a random 3×3 matrix and find its determinant.
matrix = np.random.rand(3,3)
det = np.linalg.det(matrix)
print(matrix)
print("Determinant:", det)

[[0.57088152 0.71037659 0.73082028]
 [0.94056541 0.51094481 0.5113945 ]
 [0.96795444 0.68430272 0.40256158]]
Determinant: 0.10924702965634273


In [19]:
#Create a NumPy array of 10 random integers between 1 and 100.
arr = np.random.randint(1, 101, size=10)
print(arr)

[39 81 69 72 50 60 71 37 67 37]


In [20]:
#Write a program to reshape a 1D array of size 12 into a 3×4 matrix.
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print("Original 1D array:")
print(arr)
print("\nReshaped 3x4 matrix:")
print(matrix)



Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 3x4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
#Create two 3×3 matrices and perform matrix multiplication.
a = np.arange(1, 13).reshape(3, 4)
print(a)
b = np.arange(14,26).reshape(4,3)
print(b)
m = np.matmul(a,b)
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]]
[[200 210 220]
 [496 522 548]
 [792 834 876]]


In [29]:
#Find eigenvalues and eigenvectors of a given 2×2 matrix using NumPy.
A = np.array([[4, 2],
              [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Matrix A:
[[4 2]
 [1 3]]

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [30]:
#Create a 5×5 matrix with random values and extract its diagonal elements.
matrix = np.random.rand(5, 5)
print("5x5 Random Matrix:\n", matrix)

diagonal_elements = np.diag(matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Random Matrix:
 [[0.86384199 0.8680826  0.74510154 0.94716298 0.03779399]
 [0.26035169 0.17600545 0.531126   0.84879979 0.94938534]
 [0.7410046  0.31328419 0.79305095 0.47912801 0.65291913]
 [0.97273873 0.8418689  0.71951627 0.07265434 0.68075354]
 [0.17262015 0.75847474 0.02492597 0.57746192 0.85925064]]

Diagonal Elements: [0.86384199 0.17600545 0.79305095 0.07265434 0.85925064]


In [31]:
#Generate a 1D array and normalize it (scale values between 0 and 1).
arr = np.random.randint(1, 100, size=10)
print("Original Array:", arr)
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print("Normalized Array:", normalized)

Original Array: [57 58 82 23 18 43 66 92 98 43]
Normalized Array: [0.4875 0.5    0.8    0.0625 0.     0.3125 0.6    0.925  1.     0.3125]


In [32]:
#Sort a NumPy array by row and column
arr = np.array([[34, 10, 5],
                [12, 7, 25],
                [18, 42, 3]])
print("Original Array:\n", arr)
row_sorted = np.sort(arr, axis=1)
print("\nRow-wise Sorted:\n", row_sorted)
col_sorted = np.sort(arr, axis=0)
print("\nColumn-wise Sorted:\n", col_sorted)

Original Array:
 [[34 10  5]
 [12  7 25]
 [18 42  3]]

Row-wise Sorted:
 [[ 5 10 34]
 [ 7 12 25]
 [ 3 18 42]]

Column-wise Sorted:
 [[12  7  3]
 [18 10  5]
 [34 42 25]]


In [33]:
#Find the indices of maximum and minimum values in a NumPy array
arr = np.array([12, 45, 7, 89, 23, 56])
print("Array:", arr)
print("Index of Min Value:", np.argmin(arr))
print("Index of Max Value:", np.argmax(arr))

Array: [12 45  7 89 23 56]
Index of Min Value: 2
Index of Max Value: 3


In [34]:
#Create a 2D array and flatten it using ravel() and flatten()
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:\n", arr)

print("\nFlatten using ravel():", arr.ravel())
print("Flatten using flatten():", arr.flatten())


Original Array:
 [[1 2 3]
 [4 5 6]]

Flatten using ravel(): [1 2 3 4 5 6]
Flatten using flatten(): [1 2 3 4 5 6]


In [35]:
#Create a 3×3 matrix and compute its inverse
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])

inverse_A = np.linalg.inv(A)
print("Matrix A:\n", A)
print("\nInverse of A:\n", inverse_A)

Matrix A:
 [[2 1 1]
 [1 3 2]
 [1 0 0]]

Inverse of A:
 [[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]


In [36]:
#Generate a random permutation of numbers 1 to 10
perm = np.random.permutation(np.arange(1, 11))
print("Random Permutation of 1–10:", perm)

Random Permutation of 1–10: [10  6  7  8  5  1  3  9  4  2]


In [37]:
#Replace all even numbers with -1 in array 0–20
arr = np.arange(21)
print("Original Array:", arr)
arr[arr % 2 == 0] = -1
print("Array after replacing evens with -1:", arr)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array after replacing evens with -1: [-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [38]:
#Generate a 5×5 random matrix and compute its trace
matrix = np.random.randint(1, 10, size=(5, 5))
print("5x5 Random Matrix:\n", matrix)
trace_val = np.trace(matrix)
print("\nTrace of Matrix:", trace_val)

5x5 Random Matrix:
 [[3 9 1 1 2]
 [8 9 8 5 1]
 [6 4 3 5 4]
 [3 2 7 6 9]
 [5 1 9 6 5]]

Trace of Matrix: 26


In [39]:
#Split a 1D array into 3 equal parts
arr = np.arange(9)
print("Original Array:", arr)
split_arr = np.split(arr, 3)
print("\nSplit into 3 equal parts:", split_arr)

Original Array: [0 1 2 3 4 5 6 7 8]

Split into 3 equal parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [40]:
#Create a 3D array of shape (3,3,3) and find mean across axis=0
arr3d = np.random.randint(1, 10, size=(3, 3, 3))
print("3D Array:\n", arr3d)
mean_axis0 = arr3d.mean(axis=0)
print("\nMean across axis=0:\n", mean_axis0)

3D Array:
 [[[9 2 2]
  [1 8 3]
  [5 4 9]]

 [[4 5 3]
  [4 4 3]
  [8 9 5]]

 [[7 8 6]
  [1 6 7]
  [7 4 9]]]

Mean across axis=0:
 [[6.66666667 5.         3.66666667]
 [2.         6.         4.33333333]
 [6.66666667 5.66666667 7.66666667]]


In [41]:
#Find the cumulative sum of a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

cumsum = np.cumsum(arr)
print("Cumulative Sum:", cumsum)

Original Array: [1 2 3 4 5]
Cumulative Sum: [ 1  3  6 10 15]


In [42]:
#Create a 4×4 matrix with random integers and extract upper triangular matrix
mat = np.random.randint(1, 20, size=(4, 4))
print("Original 4x4 Matrix:\n", mat)

upper_tri = np.triu(mat)
print("\nUpper Triangular Matrix:\n", upper_tri)


Original 4x4 Matrix:
 [[ 7  2  3 11]
 [ 6  5  4  4]
 [16 10 14  8]
 [16 14 18 17]]

Upper Triangular Matrix:
 [[ 7  2  3 11]
 [ 0  5  4  4]
 [ 0  0 14  8]
 [ 0  0  0 17]]


In [43]:
#Generate a 6×6 checkerboard pattern (0,1)
checkerboard = np.zeros((6, 6), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("6x6 Checkerboard Pattern:\n", checkerboard)

6x6 Checkerboard Pattern:
 [[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [44]:
#Generate a 3×3 random matrix and apply element-wise square root
mat = np.random.randint(1, 20, size=(3, 3))
print("Original 3x3 Matrix:\n", mat)

sqrt_mat = np.sqrt(mat)
print("\nElement-wise Square Root:\n", sqrt_mat)

Original 3x3 Matrix:
 [[17  2  9]
 [18 17  7]
 [14  2  2]]

Element-wise Square Root:
 [[4.12310563 1.41421356 3.        ]
 [4.24264069 4.12310563 2.64575131]
 [3.74165739 1.41421356 1.41421356]]


In [45]:
#Create a 1D array of 20 elements and reverse it without slicing
import numpy as np

arr = np.arange(1, 21)
print("Original Array:", arr)

reversed_arr = np.flip(arr)   # instead of slicing [::-1]
print("Reversed Array:", reversed_arr)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reversed Array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [46]:
#Merge two NumPy arrays vertically and horizontally
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
v_merge = np.vstack((a, b))
print("Vertical Merge:\n", v_merge)
h_merge = np.hstack((a, b))
print("\nHorizontal Merge:\n", h_merge)

Vertical Merge:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Merge:
 [[1 2 5 6]
 [3 4 7 8]]


In [47]:
#Compute row-wise and column-wise sum
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row_sum = np.sum(arr, axis=1)
col_sum = np.sum(arr, axis=0)

print("Row-wise Sum:", row_sum)
print("Column-wise Sum:", col_sum)


Row-wise Sum: [ 6 15 24]
Column-wise Sum: [12 15 18]


In [48]:
#Replace NaN values in an array with column mean
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]], dtype=float)

col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print("Array after replacing NaNs:\n", arr)


Array after replacing NaNs:
 [[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [49]:
#Compute cosine similarity between two arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

cos_sim = np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))
print("Cosine Similarity:", cos_sim)


Cosine Similarity: 0.9746318461970762


In [54]:
#Rotate a 4×4 array by 90 degrees
arr = np.arange(1, 17).reshape(4, 4)
print("Original 4x4 Array:\n", arr)
rotated = np.rot90(arr)
print("\nRotated 90°:\n", rotated)

Original 4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Rotated 90°:
 [[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]


In [55]:
#Structured NumPy array (name, age, marks)
data = np.array([('Alice', 25, 85.5),
                 ('Bob', 22, 90.0),
                 ('Charlie', 23, 78.0)],
                dtype=[('name', 'U10'), ('age', 'i4'), ('marks', 'f4')])

print("Structured Array:\n", data)
print("Names:", data['name'])
print("Ages:", data['age'])
print("Marks:", data['marks'])


Structured Array:
 [('Alice', 25, 85.5) ('Bob', 22, 90. ) ('Charlie', 23, 78. )]
Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 22 23]
Marks: [85.5 90.  78. ]


In [56]:
#Compute rank of a random 3×3 matrix
mat = np.random.randint(1, 10, size=(3, 3))
print("Matrix:\n", mat)

rank = np.linalg.matrix_rank(mat)
print("\nRank of Matrix:", rank)


Matrix:
 [[2 2 2]
 [8 3 1]
 [3 9 8]]

Rank of Matrix: 3


In [57]:
#Create a 5×5 random matrix and normalize each row to unit length
mat = np.random.rand(5, 5)
print("Original Matrix:\n", mat)
row_norms = np.linalg.norm(mat, axis=1, keepdims=True)
normalized = mat / row_norms
print("\nRow-normalized Matrix:\n", normalized)

Original Matrix:
 [[0.32178768 0.55538859 0.44568668 0.17646074 0.98804051]
 [0.19832588 0.90624307 0.62618234 0.09238152 0.85501335]
 [0.42167248 0.3388157  0.95855799 0.39092212 0.38362259]
 [0.43105227 0.52600982 0.79980838 0.03545802 0.95887187]
 [0.3286916  0.20218459 0.99568282 0.78569178 0.76250144]]

Row-normalized Matrix:
 [[0.25297626 0.43662371 0.35038057 0.13872619 0.77675688]
 [0.14050845 0.64204837 0.44363302 0.06544978 0.60575352]
 [0.34299055 0.27559443 0.77969598 0.31797806 0.31204058]
 [0.30307147 0.36983581 0.5623427  0.02493042 0.67417973]
 [0.21491738 0.13219986 0.65103442 0.51373025 0.49856708]]


In [58]:
#Check whether two arrays are equal element-wise
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 0, 4])
print("Element-wise equality:", np.equal(a, b))
print("All elements equal?:", np.array_equal(a, b))

Element-wise equality: [ True  True False  True]
All elements equal?: False


In [59]:
#Generate 1000 random numbers and compute histogram
data = np.random.randn(1000)
hist, bins = np.histogram(data, bins=10)

print("Histogram counts:", hist)
print("Bin edges:", bins)

Histogram counts: [  8  26  65 149 201 237 186  83  40   5]
Bin edges: [-2.87601769 -2.30821685 -1.74041601 -1.17261517 -0.60481434 -0.0370135
  0.53078734  1.09858818  1.66638902  2.23418985  2.80199069]


In [60]:
#Apply broadcasting to add a 1D array to 2D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr1d = np.array([10, 20, 30])

result = arr2d + arr1d
print("Broadcasted Addition:\n", result)

Broadcasted Addition:
 [[11 22 33]
 [14 25 36]]


In [61]:
#Find unique values and their counts in a NumPy array
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique_vals, counts = np.unique(arr, return_counts=True)

print("Unique values:", unique_vals)
print("Counts:", counts)

Unique values: [1 2 3 4 5]
Counts: [1 2 1 3 1]


In [62]:
#Pearson correlation coefficient of two arrays
x = np.array([10, 20, 30, 40, 50])
y = np.array([5, 15, 25, 35, 45])

corr_matrix = np.corrcoef(x, y)
pearson_corr = corr_matrix[0, 1]

print("Pearson Correlation Coefficient:", pearson_corr)

Pearson Correlation Coefficient: 1.0


In [63]:
#Compute numerical gradient of a 1D array
arr = np.array([1, 2, 4, 7, 11], dtype=float)
gradient = np.gradient(arr)

print("Original Array:", arr)
print("Numerical Gradient:", gradient)


Original Array: [ 1.  2.  4.  7. 11.]
Numerical Gradient: [1.  1.5 2.5 3.5 4. ]


In [64]:
#Perform Singular Value Decomposition (SVD)
mat = np.random.rand(3, 3)
print("Original Matrix:\n", mat)

U, S, Vt = np.linalg.svd(mat)
print("\nU Matrix:\n", U)
print("\nSingular Values:", S)
print("\nV^T Matrix:\n", Vt)

Original Matrix:
 [[0.91124073 0.65209555 0.87000722]
 [0.08536735 0.34030176 0.89271443]
 [0.33677389 0.30001369 0.25352777]]

U Matrix:
 [[-0.81971023  0.43145174 -0.37672873]
 [-0.49376063 -0.86562905  0.08298673]
 [-0.29030257  0.25403889  0.92259886]]

Singular Values: [1.7079069  0.52794147 0.06757045]

V^T Matrix:
 [[-0.51927345 -0.46235058 -0.71873989]
 [ 0.76677742  0.11930833 -0.63072808]
 [-0.37736915  0.87863386 -0.29256634]]
